In [ ]:
!pip install py_vollib QuantLib-Python mibian plotly --quiet

In [ ]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

from py_vollib.black_scholes.implied_volatility import implied_volatility
from py_vollib.black_scholes.greeks.analytical import delta, gamma, theta, vega

import QuantLib as ql
import mibian

from IPython.display import display

/tmp/ipykernel_704/1430710626.py:6: DeprecationWarning: py_vollib is deprecated and will be removed in a future release; please import from vollib instead.
  from py_vollib.black_scholes.implied_volatility import implied_volatility

In [ ]:
  import pandas as pd

csv_path = "/content/bankniftyoptchain/"

import os

print(os.listdir(csv_path))

['.ipynb_checkpoints', 'option-chain.csv']

In [ ]:
df = pd.read_csv("/content/bankniftyoptchain/option-chain.csv")

print(df.head())

print(df.columns)

print(df.shape)

df.info()

                                                                                                                                               CALLS  \
NaN OI  CHNG IN OI VOLUME IV    LTP CHNG BID QTY BID       ASK       ASK QTY STRIKE    BID QTY BID  ASK  ASK QTY CHNG  LTP  IV    VOLUME  CHNG IN OI
    721 -          -      -     -   -    300     11,198.75 13,035.80 300     46,000.00 750     3.40 3.55 600     -     3.55 35.55 385            -28
    46  -          -      42.99 -   -    300     10,750.45 12,503.45 300     46,500.00 300     3.80 4.60 330     -0.35 3.55 34.20 16              -1
    206 -          -      -     -   -    30      11,315.60 11,800.45 30      47,000.00 4,620   5.25 5.30 180     1.25  5.25 34.09 544            147
    -   -          -      -     -   -    300     9,924.00  11,464.35 300     47,500.00 120     5.35 6.15 300     -0.30 4.80 32.31 16               2

                                                                                                                                         Unnamed: 1  \
NaN OI  CHNG IN OI VOLUME IV    LTP CHNG BID QTY BID       ASK       ASK QTY STRIKE    BID QTY BID  ASK  ASK QTY CHNG  LTP  IV    VOLUME         OI
    721 -          -      -     -   -    300     11,198.75 13,035.80 300     46,000.00 750     3.40 3.55 600     -     3.55 35.55 385         2,345
    46  -          -      42.99 -   -    300     10,750.45 12,503.45 300     46,500.00 300     3.80 4.60 330     -0.35 3.55 34.20 16            164
    206 -          -      -     -   -    30      11,315.60 11,800.45 30      47,000.00 4,620   5.25 5.30 180     1.25  5.25 34.09 544         1,069
    -   -          -      -     -   -    300     9,924.00  11,464.35 300     47,500.00 120     5.35 6.15 300     -0.30 4.80 32.31 16            253

                                                                                                                                          PUTS
NaN OI  CHNG IN OI VOLUME IV    LTP CHNG BID QTY BID       ASK       ASK QTY STRIKE    BID QTY BID  ASK  ASK QTY CHNG  LTP  IV    VOLUME   NaN
    721 -          -      -     -   -    300     11,198.75 13,035.80 300     46,000.00 750     3.40 3.55 600     -     3.55 35.55 385      NaN
    46  -          -      42.99 -   -    300     10,750.45 12,503.45 300     46,500.00 300     3.80 4.60 330     -0.35 3.55 34.20 16       NaN
    206 -          -      -     -   -    30      11,315.60 11,800.45 30      47,000.00 4,620   5.25 5.30 180     1.25  5.25 34.09 544      NaN
    -   -          -      -     -   -    300     9,924.00  11,464.35 300     47,500.00 120     5.35 6.15 300     -0.30 4.80 32.31 16       NaN
Index(['CALLS', 'Unnamed: 1', 'PUTS'], dtype='object')
(171, 3)
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 171 entries, (nan, 'OI', 'CHNG IN OI', 'VOLUME', 'IV', 'LTP', 'CHNG', 'BID QTY', 'BID', 'ASK', 'ASK QTY', 'STRIKE', 'BID QTY', 'BID', 'ASK', 'ASK QTY', 'CHNG', 'LTP', 'IV', 'VOLUME') to (nan, '3,239', '-969', '3,061', '17.76', '5.05', '0.90', '90', '5.05', '5.15', '90', '65,500.00', '300', '6,373.55', '7,202.15', '330', '-', '-', '-', '-')
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CALLS       171 non-null    object
 1   Unnamed: 1  171 non-null    object
 2   PUTS        0 non-null      float64
dtypes: float64(1), object(2)
memory usage: 76.4+ KB

In [ ]:
with open("/content/bankniftyoptchain/option-chain.csv", "r") as f:
    for i in range(15):
        print(f.readline())

CALLS,,PUTS

,OI,CHNG IN OI,VOLUME,IV,LTP,CHNG,BID QTY,BID,ASK,ASK QTY,STRIKE,BID QTY,BID,ASK,ASK QTY,CHNG,LTP,IV,VOLUME,CHNG IN OI,OI,

,721,-,-,-,-,-,300,"11,198.75","13,035.80",300,"46,000.00",750,3.40,3.55,600,-,3.55,35.55,385,-28,"2,345",

,46,-,-,42.99,-,-,300,"10,750.45","12,503.45",300,"46,500.00",300,3.80,4.60,330,-0.35,3.55,34.20,16,-1,164,

,206,-,-,-,-,-,30,"11,315.60","11,800.45",30,"47,000.00","4,620",5.25,5.30,180,1.25,5.25,34.09,544,147,"1,069",

,-,-,-,-,-,-,300,"9,924.00","11,464.35",300,"47,500.00",120,5.35,6.15,300,-0.30,4.80,32.31,16,2,253,

,-,-,-,-,-,-,300,"9,774.20","11,365.55",300,"47,600.00",120,4.95,7.00,30,-1.50,6.20,32.90,1,-,22,

,-,-,-,-,-,-,300,"9,731.20","11,255.70",300,"47,700.00",150,4.55,6.50,120,-,-,31.31,-,-,13,

,-,-,-,-,-,-,300,"9,636.20","11,147.30",300,"47,800.00",180,4.85,7.00,30,-1.20,4.60,31.30,40,-18,17,

,-,-,-,-,-,-,300,"9,497.55","11,053.90",300,"47,900.00",30,6.10,6.50,420,0.10,6.30,31.44,5,-1,20,

,233,-,-,-,-,-,30,"10,408.40","10,533.95",30,"48,000.00",30,6.05,6.20,120,1.05,6.20,31.85,294,26,"1,448",

,-,-,-,-,-,-,300,"9,369.60","10,847.95",300,"48,100.00",30,6.45,6.85,90,-0.95,6.30,31.47,6,-,9,

,-,-,-,-,-,-,300,"9,224.50","10,746.45",300,"48,200.00",120,6.10,7.90,600,-0.70,6.00,31.01,19,-,190,

,-,-,-,-,-,-,300,"9,190.20","10,640.05",300,"48,300.00",150,5.50,7.50,120,-,-,30.00,-,-,8,

,-,-,-,-,-,-,300,"9,061.40","10,538.90",300,"48,400.00",150,5.40,7.55,120,-,-,29.72,-,-,13,

In [ ]:
import pandas as pd

raw = pd.read_csv(
    "/content/bankniftyoptchain/option-chain.csv",
    header=None
)

display(raw.head(15))

ParserError: Error tokenizing data. C error: Expected 3 fields in line 2, saw 23

In [ ]:
header=1
header=[0,1]

In [ ]:
import pandas as pd

df = pd.read_csv(
    "/content/bankniftyoptchain/option-chain.csv",
    skiprows=1
)

display(df.head())
print(df.columns)

,Unnamed: 0,OI,CHNG IN OI,VOLUME,IV,LTP,CHNG,BID QTY,BID,ASK,...,BID.1,ASK.1,ASK QTY.1,CHNG.1,LTP.1,IV.1,VOLUME.1,CHNG IN OI.1,OI.1,Unnamed: 22
0,NaN,721,-,-,-,-,-,300,"11,198.75","13,035.80",...,3.40,3.55,600,-,3.55,35.55,385,-28,"2,345",NaN
1,NaN,46,-,-,42.99,-,-,300,"10,750.45","12,503.45",...,3.80,4.60,330,-0.35,3.55,34.20,16,-1,164,NaN
2,NaN,206,-,-,-,-,-,30,"11,315.60","11,800.45",...,5.25,5.30,180,1.25,5.25,34.09,544,147,"1,069",NaN
3,NaN,-,-,-,-,-,-,300,"9,924.00","11,464.35",...,5.35,6.15,300,-0.30,4.80,32.31,16,2,253,NaN
4,NaN,-,-,-,-,-,-,300,"9,774.20","11,365.55",...,4.95,7.00,30,-1.50,6.20,32.90,1,-,22,NaN

Index(['Unnamed: 0', 'OI', 'CHNG IN OI', 'VOLUME', 'IV', 'LTP', 'CHNG',
       'BID QTY', 'BID', 'ASK', 'ASK QTY', 'STRIKE', 'BID QTY.1', 'BID.1',
       'ASK.1', 'ASK QTY.1', 'CHNG.1', 'LTP.1', 'IV.1', 'VOLUME.1',
       'CHNG IN OI.1', 'OI.1', 'Unnamed: 22'],
      dtype='object')

In [ ]:
df = pd.read_csv(
    "/content/bankniftyoptchain/option-chain.csv",
    skiprows=1,
    engine="python"
)

display(df.head())

,Unnamed: 0,OI,CHNG IN OI,VOLUME,IV,LTP,CHNG,BID QTY,BID,ASK,...,BID.1,ASK.1,ASK QTY.1,CHNG.1,LTP.1,IV.1,VOLUME.1,CHNG IN OI.1,OI.1,Unnamed: 22
0,NaN,721,-,-,-,-,-,300,"11,198.75","13,035.80",...,3.40,3.55,600,-,3.55,35.55,385,-28,"2,345",NaN
1,NaN,46,-,-,42.99,-,-,300,"10,750.45","12,503.45",...,3.80,4.60,330,-0.35,3.55,34.20,16,-1,164,NaN
2,NaN,206,-,-,-,-,-,30,"11,315.60","11,800.45",...,5.25,5.30,180,1.25,5.25,34.09,544,147,"1,069",NaN
3,NaN,-,-,-,-,-,-,300,"9,924.00","11,464.35",...,5.35,6.15,300,-0.30,4.80,32.31,16,2,253,NaN
4,NaN,-,-,-,-,-,-,300,"9,774.20","11,365.55",...,4.95,7.00,30,-1.50,6.20,32.90,1,-,22,NaN

In [ ]:
df.columns = [
    "CALL_OI",
    "CALL_CHNG_OI",
    "CALL_VOLUME",
    "CALL_IV",
    "CALL_LTP",
    "CALL_CHNG",
    "CALL_BID_QTY",
    "CALL_BID",
    "CALL_ASK",
    "CALL_ASK_QTY",
    "STRIKE",
    "PUT_BID_QTY",
    "PUT_BID",
    "PUT_ASK",
    "PUT_ASK_QTY",
    "PUT_CHNG",
    "PUT_LTP",
    "PUT_IV",
    "PUT_VOLUME",
    "PUT_CHNG_OI",
    "PUT_OI",
    "IGNORE",
    "EXTRA"
]

display(df.head())

,CALL_OI,CALL_CHNG_OI,CALL_VOLUME,CALL_IV,CALL_LTP,CALL_CHNG,CALL_BID_QTY,CALL_BID,CALL_ASK,CALL_ASK_QTY,...,PUT_ASK,PUT_ASK_QTY,PUT_CHNG,PUT_LTP,PUT_IV,PUT_VOLUME,PUT_CHNG_OI,PUT_OI,IGNORE,EXTRA
0,NaN,721,-,-,-,-,-,300,"11,198.75","13,035.80",...,3.40,3.55,600,-,3.55,35.55,385,-28,"2,345",NaN
1,NaN,46,-,-,42.99,-,-,300,"10,750.45","12,503.45",...,3.80,4.60,330,-0.35,3.55,34.20,16,-1,164,NaN
2,NaN,206,-,-,-,-,-,30,"11,315.60","11,800.45",...,5.25,5.30,180,1.25,5.25,34.09,544,147,"1,069",NaN
3,NaN,-,-,-,-,-,-,300,"9,924.00","11,464.35",...,5.35,6.15,300,-0.30,4.80,32.31,16,2,253,NaN
4,NaN,-,-,-,-,-,-,300,"9,774.20","11,365.55",...,4.95,7.00,30,-1.50,6.20,32.90,1,-,22,NaN

In [ ]:
df = df.drop(columns=["IGNORE", "EXTRA"], errors="ignore")

display(df.head())

,CALL_OI,CALL_CHNG_OI,CALL_VOLUME,CALL_IV,CALL_LTP,CALL_CHNG,CALL_BID_QTY,CALL_BID,CALL_ASK,CALL_ASK_QTY,...,PUT_BID_QTY,PUT_BID,PUT_ASK,PUT_ASK_QTY,PUT_CHNG,PUT_LTP,PUT_IV,PUT_VOLUME,PUT_CHNG_OI,PUT_OI
0,NaN,721,-,-,-,-,-,300,"11,198.75","13,035.80",...,"46,000.00",750,3.40,3.55,600,-,3.55,35.55,385,-28
1,NaN,46,-,-,42.99,-,-,300,"10,750.45","12,503.45",...,"46,500.00",300,3.80,4.60,330,-0.35,3.55,34.20,16,-1
2,NaN,206,-,-,-,-,-,30,"11,315.60","11,800.45",...,"47,000.00","4,620",5.25,5.30,180,1.25,5.25,34.09,544,147
3,NaN,-,-,-,-,-,-,300,"9,924.00","11,464.35",...,"47,500.00",120,5.35,6.15,300,-0.30,4.80,32.31,16,2
4,NaN,-,-,-,-,-,-,300,"9,774.20","11,365.55",...,"47,600.00",120,4.95,7.00,30,-1.50,6.20,32.90,1,-

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CALL_OI       0 non-null      float64
 1   CALL_CHNG_OI  170 non-null    object
 2   CALL_VOLUME   170 non-null    object
 3   CALL_IV       170 non-null    object
 4   CALL_LTP      170 non-null    object
 5   CALL_CHNG     170 non-null    object
 6   CALL_BID_QTY  170 non-null    object
 7   CALL_BID      170 non-null    int64
 8   CALL_ASK      170 non-null    object
 9   CALL_ASK_QTY  170 non-null    object
 10  STRIKE        170 non-null    int64
 11  PUT_BID_QTY   170 non-null    object
 12  PUT_BID       170 non-null    object
 13  PUT_ASK       170 non-null    object
 14  PUT_ASK_QTY   170 non-null    object
 15  PUT_CHNG      170 non-null    int64
 16  PUT_LTP       170 non-null    object
 17  PUT_IV        170 non-null    object
 18  PUT_VOLUME    170 non-null    object
 19  PUT_CHNG_OI   170 non-null    object
 20  PUT_OI        170 non-null    object
dtypes: float64(1), int64(3), object(17)
memory usage: 28.0+ KB

In [ ]:
for col in df.columns:
    if col != "STRIKE":
        df[col] = pd.to_numeric(df[col], errors="coerce")

df["STRIKE"] = pd.to_numeric(df["STRIKE"], errors="coerce")

display(df.head())

,CALL_OI,CALL_CHNG_OI,CALL_VOLUME,CALL_IV,CALL_LTP,CALL_CHNG,CALL_BID_QTY,CALL_BID,CALL_ASK,CALL_ASK_QTY,...,PUT_BID_QTY,PUT_BID,PUT_ASK,PUT_ASK_QTY,PUT_CHNG,PUT_LTP,PUT_IV,PUT_VOLUME,PUT_CHNG_OI,PUT_OI
0,NaN,721.0,NaN,NaN,NaN,NaN,NaN,300,NaN,NaN,...,NaN,750.0,3.40,3.55,600,NaN,3.55,35.55,385.0,-28.0
1,NaN,46.0,NaN,NaN,42.99,NaN,NaN,300,NaN,NaN,...,NaN,300.0,3.80,4.60,330,-0.35,3.55,34.20,16.0,-1.0
2,NaN,206.0,NaN,NaN,NaN,NaN,NaN,30,NaN,NaN,...,NaN,NaN,5.25,5.30,180,1.25,5.25,34.09,544.0,147.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300,NaN,NaN,...,NaN,120.0,5.35,6.15,300,-0.30,4.80,32.31,16.0,2.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300,NaN,NaN,...,NaN,120.0,4.95,7.00,30,-1.50,6.20,32.90,1.0,NaN

In [ ]:
for col in df.columns:
    if col != "STRIKE":
        df[col] = pd.to_numeric(df[col], errors="coerce")

df["STRIKE"] = pd.to_numeric(df["STRIKE"], errors="coerce")

display(df.head())

,CALL_OI,CALL_CHNG_OI,CALL_VOLUME,CALL_IV,CALL_LTP,CALL_CHNG,CALL_BID_QTY,CALL_BID,CALL_ASK,CALL_ASK_QTY,...,PUT_BID_QTY,PUT_BID,PUT_ASK,PUT_ASK_QTY,PUT_CHNG,PUT_LTP,PUT_IV,PUT_VOLUME,PUT_CHNG_OI,PUT_OI
0,NaN,721.0,NaN,NaN,NaN,NaN,NaN,300,NaN,NaN,...,NaN,750.0,3.40,3.55,600,NaN,3.55,35.55,385.0,-28.0
1,NaN,46.0,NaN,NaN,42.99,NaN,NaN,300,NaN,NaN,...,NaN,300.0,3.80,4.60,330,-0.35,3.55,34.20,16.0,-1.0
2,NaN,206.0,NaN,NaN,NaN,NaN,NaN,30,NaN,NaN,...,NaN,NaN,5.25,5.30,180,1.25,5.25,34.09,544.0,147.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300,NaN,NaN,...,NaN,120.0,5.35,6.15,300,-0.30,4.80,32.31,16.0,2.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300,NaN,NaN,...,NaN,120.0,4.95,7.00,30,-1.50,6.20,32.90,1.0,NaN

In [ ]:
df = load_nse_option_chain("option-chain.csv")

NameError: name 'load_nse_option_chain' is not defined

In [ ]:
print("Number of columns:", len(df.columns))

for i, col in enumerate(df.columns):
    print(i, ":", col)

Number of columns: 21
0 : CALL_OI
1 : CALL_CHNG_OI
2 : CALL_VOLUME
3 : CALL_IV
4 : CALL_LTP
5 : CALL_CHNG
6 : CALL_BID_QTY
7 : CALL_BID
8 : CALL_ASK
9 : CALL_ASK_QTY
10 : STRIKE
11 : PUT_BID_QTY
12 : PUT_BID
13 : PUT_ASK
14 : PUT_ASK_QTY
15 : PUT_CHNG
16 : PUT_LTP
17 : PUT_IV
18 : PUT_VOLUME
19 : PUT_CHNG_OI
20 : PUT_OI

In [ ]:
print(df.iloc[0].tolist())

[nan, 721.0, nan, nan, nan, nan, nan, 300.0, nan, nan, 300.0, nan, 750.0, 3.4, 3.55, 600.0, nan, 3.55, 35.55, 385.0, -28.0]

In [1]:
def load_nse_option_chain(csv_file):
    ...
    return df

In [2]:
df = load_nse_option_chain("/content/bankniftyoptchain/option-chain.csv")

NameError: name 'df' is not defined

In [7]:
import pandas as pd
import numpy as np

def load_nse_option_chain(csv_file):

    # Read CSV (skip the CALLS/PUTS row)
    df = pd.read_csv(
        csv_file,
        skiprows=1,
        engine="python"
    )

    # Rename columns
    df.columns = [
        "EMPTY",
        "CALL_OI",
        "CALL_CHNG_OI",
        "CALL_VOLUME",
        "CALL_IV",
        "CALL_LTP",
        "CALL_CHNG",
        "CALL_BID_QTY",
        "CALL_BID",
        "CALL_ASK",
        "CALL_ASK_QTY",
        "STRIKE",
        "PUT_BID_QTY",
        "PUT_BID",
        "PUT_ASK",
        "PUT_ASK_QTY",
        "PUT_CHNG",
        "PUT_LTP",
        "PUT_IV",
        "PUT_VOLUME",
        "PUT_CHNG_OI",
        "PUT_OI",
        "EMPTY2"
    ]

    # Remove unused columns
    df = df.drop(columns=["EMPTY", "EMPTY2"], errors="ignore")

    # Replace "-" with NaN
    df = df.replace("-", np.nan)

    # Remove commas from numbers
    df = df.replace(",", "", regex=True)

    # Convert everything to numeric
    for col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    return df

In [8]:
df = load_nse_option_chain(
    "/content/bankniftyoptchain/option-chain.csv"
)

df.head()

,CALL_OI,CALL_CHNG_OI,CALL_VOLUME,CALL_IV,CALL_LTP,CALL_CHNG,CALL_BID_QTY,CALL_BID,CALL_ASK,CALL_ASK_QTY,...,PUT_BID_QTY,PUT_BID,PUT_ASK,PUT_ASK_QTY,PUT_CHNG,PUT_LTP,PUT_IV,PUT_VOLUME,PUT_CHNG_OI,PUT_OI
0,721.0,NaN,NaN,NaN,NaN,NaN,300,11359.85,12843.60,300.0,...,1020,3.15,3.30,60,-0.20,3.35,35.27,763.0,-45.0,2328.0
1,46.0,NaN,NaN,42.99,NaN,NaN,300,10899.95,12311.45,300.0,...,600,3.35,4.20,300,0.20,4.10,34.51,39.0,-2.0,163.0
2,206.0,NaN,NaN,NaN,NaN,NaN,30,11375.60,11675.15,300.0,...,10440,3.75,3.95,30,-0.25,3.75,32.76,1709.0,408.0,1330.0
3,NaN,NaN,NaN,NaN,NaN,NaN,300,9990.50,11286.95,300.0,...,300,4.25,5.00,300,-0.10,5.00,32.26,47.0,8.0,259.0
4,NaN,NaN,NaN,NaN,NaN,NaN,300,9891.80,11187.55,300.0,...,600,4.20,6.50,600,-1.45,6.25,32.74,9.0,-1.0,21.0

In [9]:
import os

print(os.listdir("/content/bankniftyoptchain"))

['.ipynb_checkpoints', 'option-chain.csv']

In [10]:
# Replace '--' with NaN
df.replace("--", np.nan, inplace=True)

# Convert every column except STRIKE to numeric
for col in df.columns:
    if col != "STRIKE":
        df[col] = pd.to_numeric(df[col], errors="coerce")

# STRIKE should also be numeric
df["STRIKE"] = pd.to_numeric(df["STRIKE"])

display(df.head())
df.info()

,CALL_OI,CALL_CHNG_OI,CALL_VOLUME,CALL_IV,CALL_LTP,CALL_CHNG,CALL_BID_QTY,CALL_BID,CALL_ASK,CALL_ASK_QTY,...,PUT_BID_QTY,PUT_BID,PUT_ASK,PUT_ASK_QTY,PUT_CHNG,PUT_LTP,PUT_IV,PUT_VOLUME,PUT_CHNG_OI,PUT_OI
0,721.0,NaN,NaN,NaN,NaN,NaN,300,11359.85,12843.60,300.0,...,1020,3.15,3.30,60,-0.20,3.35,35.27,763.0,-45.0,2328.0
1,46.0,NaN,NaN,42.99,NaN,NaN,300,10899.95,12311.45,300.0,...,600,3.35,4.20,300,0.20,4.10,34.51,39.0,-2.0,163.0
2,206.0,NaN,NaN,NaN,NaN,NaN,30,11375.60,11675.15,300.0,...,10440,3.75,3.95,30,-0.25,3.75,32.76,1709.0,408.0,1330.0
3,NaN,NaN,NaN,NaN,NaN,NaN,300,9990.50,11286.95,300.0,...,300,4.25,5.00,300,-0.10,5.00,32.26,47.0,8.0,259.0
4,NaN,NaN,NaN,NaN,NaN,NaN,300,9891.80,11187.55,300.0,...,600,4.20,6.50,600,-1.45,6.25,32.74,9.0,-1.0,21.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CALL_OI       116 non-null    float64
 1   CALL_CHNG_OI  79 non-null     float64
 2   CALL_VOLUME   89 non-null     float64
 3   CALL_IV       89 non-null     float64
 4   CALL_LTP      89 non-null     float64
 5   CALL_CHNG     89 non-null     float64
 6   CALL_BID_QTY  170 non-null    int64
 7   CALL_BID      170 non-null    float64
 8   CALL_ASK      166 non-null    float64
 9   CALL_ASK_QTY  166 non-null    float64
 10  STRIKE        170 non-null    float64
 11  PUT_BID_QTY   170 non-null    int64
 12  PUT_BID       170 non-null    float64
 13  PUT_ASK       170 non-null    float64
 14  PUT_ASK_QTY   170 non-null    int64
 15  PUT_CHNG      142 non-null    float64
 16  PUT_LTP       143 non-null    float64
 17  PUT_IV        150 non-null    float64
 18  PUT_VOLUME    143 non-null    float64
 19  PUT_CHNG_OI   130 non-null    float64
 20  PUT_OI        154 non-null    float64
dtypes: float64(18), int64(3)
memory usage: 28.0 KB

In [12]:
def market_summary(df):
    summary = {}

    # Total Open Interest
    summary["Total Call OI"] = df["CALL_OI"].sum()
    summary["Total Put OI"] = df["PUT_OI"].sum()

    # Put Call Ratio
    if summary["Total Call OI"] > 0:
        summary["PCR"] = summary["Total Put OI"] / summary["Total Call OI"]
    else:
        summary["PCR"] = None

    # Highest Call OI
    call_row = df.loc[df["CALL_OI"].idxmax()]
    summary["Highest Call OI"] = call_row["CALL_OI"]
    summary["Call Resistance"] = call_row["STRIKE"]

    # Highest Put OI
    put_row = df.loc[df["PUT_OI"].idxmax()]
    summary["Highest Put OI"] = put_row["PUT_OI"]
    summary["Put Support"] = put_row["STRIKE"]

    return summary

In [13]:
summary = market_summary(df)

for k, v in summary.items():
    print(f"{k:20} : {v}")

Total Call OI        : 417274.0
Total Put OI         : 371746.0
PCR                  : 0.8908918360597593
Highest Call OI      : 66480.0
Call Resistance      : 60000.0
Highest Put OI       : 42060.0
Put Support          : 58000.0

In [14]:
def estimate_atm(df):
    temp = df.copy()

    temp["DIFF"] = (temp["CALL_LTP"] - temp["PUT_LTP"]).abs()

    atm = temp.loc[temp["DIFF"].idxmin()]

    return atm["STRIKE"]

In [15]:
print("Estimated ATM Strike:", estimate_atm(df))

Estimated ATM Strike: 58500.0

In [16]:
import plotly.graph_objects as go

fig = go.Figure()

# Call OI (Green)
fig.add_trace(
    go.Bar(
        x=df["STRIKE"],
        y=df["CALL_OI"],
        name="Call OI",
        marker_color="green",
        opacity=0.75,
    )
)

# Put OI (Red)
fig.add_trace(
    go.Bar(
        x=df["STRIKE"],
        y=df["PUT_OI"],
        name="Put OI",
        marker_color="red",
        opacity=0.75,
    )
)

fig.update_layout(
    title="BANKNIFTY Open Interest",
    xaxis_title="Strike Price",
    yaxis_title="Open Interest",
    barmode="group",
    template="plotly_white",
    hovermode="x unified",
    height=600,
)

fig.show()

In [17]:
fig = go.Figure()

fig.add_trace(
    go.Bar(
        x=df["STRIKE"],
        y=df["CALL_OI"],
        name="Call OI",
        marker_color="green"
    )
)

fig.add_trace(
    go.Bar(
        x=df["STRIKE"],
        y=-df["PUT_OI"],
        name="Put OI",
        marker_color="red"
    )
)

fig.update_layout(
    title="Open Interest Distribution",
    xaxis_title="Strike",
    yaxis_title="OI",
    template="plotly_white",
    hovermode="x unified",
    height=650
)

fig.show()

In [18]:
atm = estimate_atm(df)

fig.add_vline(
    x=atm,
    line_width=2,
    line_dash="dash",
    line_color="blue",
    annotation_text="ATM",
    annotation_position="top"
)

fig.show()

In [19]:
summary = market_summary(df)

support = summary["Put Support"]
resistance = summary["Call Resistance"]

In [20]:
fig.add_vline(
    x=support,
    line_color="green",
    line_width=2,
    annotation_text="Support"
)

fig.add_vline(
    x=resistance,
    line_color="red",
    line_width=2,
    annotation_text="Resistance"
)